# I need to get descriptors for systems with TgDHFR protein

In [1]:
import pandas as pd
from padelpy import from_smiles

In [2]:
df = pd.read_csv('./1-Training_Database/V2-combined_bd_chmbl_unique.csv')
df.head(2)

,cid,Smiles,Standard Value,pIC50 Value
0,23647975.0,COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O,34.0,7.468521
1,5578.0,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,2722.0,5.565112

In [3]:
df.columns

Index(['cid', 'Smiles', 'Standard Value', 'pIC50 Value'], dtype='object')

# 1. Dataframe of the unique ligands:

In [7]:
unique_smiles = df['Smiles'].unique()

len(unique_smiles)

870

In [8]:
%%time
import pandas as pd
from padelpy import padeldescriptor

# Write unique SMILES to a file with SMILES strings as their names
with open('unique_smiles.smi', 'w') as f:
    for smile in unique_smiles:
        f.write(f"{smile} {smile}\n")  # Write SMILES strings as names

# Calculate descriptors using padeldescriptor
padeldescriptor(
    mol_dir='unique_smiles.smi',
    d_file='descriptors_ligand-tmp.csv',
    fingerprints=True,
    d_2d=True)

# Read the results from the CSV file and create the DataFrame
df_ligands = pd.read_csv('descriptors_ligand-tmp.csv')

# Ensure the first column is SMILES
df_ligands.rename(columns={'Name': 'Smiles'}, inplace=True)

# Save the DataFrame to a new CSV file
df_ligands.to_csv('V2-TgDHFR-2d-descriptors_ligand.csv', index=False)

# Display the DataFrame
df_ligands

CPU times: user 1.27 s, sys: 49.6 ms, total: 1.32 s
Wall time: 37.4 s

,Smiles,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O,1,-0.9874,0.974959,55.7857,55.717446,12,12,49,27,...,0,0,0,0,0,0,0,0,0,0
1,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,0,-1.1990,1.437601,34.9926,43.448274,12,12,39,21,...,0,0,0,0,0,0,0,0,0,0
2,COc1ccc(OC)c(Cc2cnc3nc(N)nc(N)c3c2C)c1,0,-0.5052,0.255227,33.1789,49.693067,16,17,43,24,...,0,0,0,0,0,0,0,0,0,0
3,COc1ccc(OCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,1,-1.0889,1.185703,46.8745,59.244239,16,17,52,29,...,0,0,0,0,0,0,0,0,0,0
4,COc1ccc(OCCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,1,-1.3769,1.895854,49.7861,62.337825,16,17,55,30,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,COc1ccc(CCCOc2ccccc2C(=O)O)cc1Cc1cnc(N)nc1N,1,-1.7033,2.901231,41.6886,62.331032,18,18,54,30,...,0,0,0,0,0,0,0,0,0,0
866,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)...,2,-1.3590,1.846881,68.9621,59.837446,14,16,53,31,...,0,0,0,0,0,0,0,0,0,0
867,Cc1nc(N)nc2c1c(CCc1ccc(C(=O)N[C@@H](CCC(=O)O)C...,2,-1.6855,2.840910,59.9593,78.126997,21,22,67,38,...,0,0,0,0,0,0,0,0,0,0
868,COc1cc(-c2nc3c(N)nc(N)nc3[nH]2)cc(OC)c1O,0,-2.4841,6.170753,28.9404,41.221102,15,17,36,22,...,0,0,0,0,0,0,0,0,0,0
869,CN(Cc1coc2nc(N)nc(N)c12)c1ccc(C(=O)N[C@@H](CCC...,2,-3.0515,9.311652,56.0339,61.281446,15,16,54,32,...,0,0,0,0,0,0,0,0,0,0