# BindignDB database

# 1. Reading Database

In [1]:
import pandas as pd
import logging

# Reading TSV file
file_path = r'/expanse/lustre/projects/uci148/nvs/Paper/BindingDB_All_202406.tsv'


def skip_bad_line(line):
    pass

df_org = pd.read_csv(file_path, delimiter='\t', on_bad_lines=skip_bad_line, engine='python')

In [2]:
df_org.head(2)

,BindingDB Reactant_set_id,Ligand SMILES,Ligand InChI,Ligand InChI Key,BindingDB MonomerID,BindingDB Ligand Name,Target Name,Target Source Organism According to Curator or DataSource,Ki (nM),IC50 (nM),...,UniProt (SwissProt) Recommended Name of Target Chain.12,UniProt (SwissProt) Entry Name of Target Chain.12,UniProt (SwissProt) Primary ID of Target Chain.12,UniProt (SwissProt) Secondary ID(s) of Target Chain.12,UniProt (SwissProt) Alternative ID(s) of Target Chain.12,UniProt (TrEMBL) Submitted Name of Target Chain.12,UniProt (TrEMBL) Entry Name of Target Chain.12,UniProt (TrEMBL) Primary ID of Target Chain.12,UniProt (TrEMBL) Secondary ID(s) of Target Chain.12,UniProt (TrEMBL) Alternative ID(s) of Target Chain.12
0,1,O[C@@H]1[C@@H](O)[C@@H](Cc2ccccc2)N(CCCCCC(O)=...,InChI=1S/C31H42N2O7/c34-27(35)17-9-3-11-19-32-...,XGEGDSLAQZJGCW-HHGOQMMWSA-N,608734,"6-[(4R,5S,6S,7R)-4,7-dibenzyl-3-(5-carboxypent...",Dimer of Gag-Pol polyprotein [501-599],Human immunodeficiency virus 1,0.24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,O[C@@H]1[C@@H](O)[C@@H](Cc2ccccc2)N(C\C=C\c2cn...,InChI=1S/C31H34N6O3/c38-29-27(17-23-9-3-1-4-10...,UZLMEAPBHYEHAC-UNTBESQGSA-N,22,"(4R,5S,6S,7R)-4,7-dibenzyl-5,6-dihydroxy-1,3-b...",Dimer of Gag-Pol polyprotein [501-599],Human immunodeficiency virus 1,0.25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_org.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2874595 entries, 0 to 2874594
Data columns (total 194 columns):
 #    Column                                                                Non-Null Count    Dtype
---   ------                                                                --------------    -----
 0    BindingDB Reactant_set_id                                             2874595 non-null  int64
 1    Ligand SMILES                                                         2874594 non-null  object
 2    Ligand InChI                                                          2757032 non-null  object
 3    Ligand InChI Key                                                      2757032 non-null  object
 4    BindingDB MonomerID                                                   2874595 non-null  int64
 5    BindingDB Ligand Name                                                 2874595 non-null  object
 6    Target Name                                                           2874595 non-null  object
 7    Target Source Organism According to Curator or DataSource             1862554 non-null  object
 8    Ki (nM)                                                               588605 non-null   object
 9    IC50 (nM)                                                             1916275 non-null  object
 10   Kd (nM)                                                               108101 non-null   object
 11   EC50 (nM)                                                             264535 non-null   object
 12   kon (M-1-s-1)                                                         1006 non-null     object
 13   koff (s-1)                                                            986 non-null      object
 14   pH                                                                    215260 non-null   float64
 15   Temp (C)                                                              200904 non-null   object
 16   Curation/DataSource                                                   2874595 non-null  object
 17   Article DOI                                                           1552970 non-null  object
 18   BindingDB Entry DOI                                                   2868474 non-null  object
 19   PMID                                                                  1613240 non-null  float64
 20   PubChem AID                                                           1156700 non-null  object
 21   Patent Number                                                         1102068 non-null  object
 22   Authors                                                               2838406 non-null  object
 23   Institution                                                           2838406 non-null  object
 24   Link to Ligand in BindingDB                                           2874595 non-null  object
 25   Link to Target in BindingDB                                           2874595 non-null  object
 26   Link to Ligand-Target Pair in BindingDB                               2874595 non-null  object
 27   Ligand HET ID in PDB                                                  170336 non-null   object
 28   PDB ID(s) for Ligand-Target Complex                                   151792 non-null   object
 29   PubChem CID                                                           2838394 non-null  float64
 30   PubChem SID                                                           2838618 non-null  float64
 31   ChEBI ID of Ligand                                                    96611 non-null    float64
 32   ChEMBL ID of Ligand                                                   1105117 non-null  object
 33   DrugBank ID of Ligand                                                 87177 non-null    object
 34   IUPHAR_GRAC ID of Ligand                                              107963 non-null   float64
 35   KEGG ID of Ligand                                                     99767 non-null    object
 36   ZINC ID of Ligand                                                     1166620 non-null  object
 37   Number of Protein Chains in Target (>1 implies a multichain complex)  2874595 non-null  int64
 38   BindingDB Target Chain Sequence                                       2874595 non-null  object
 39   PDB ID(s) of Target Chain                                             2257608 non-null  object
 40   UniProt (SwissProt) Recommended Name of Target Chain                  2790042 non-null  object
 41   UniProt (SwissProt) Entry Name of Target Chain                        2789232 non-null  object
 42   UniProt (SwissProt) Primary ID of Target Chain                        2790042 non-null  object
 43   UniProt (SwissProt) Secondary ID(s) of Target Chain                   2504760 non-null  object
 44   UniProt (SwissProt) Alternative ID(s) of Target Chain                 0 non-null        float64
 45   UniProt (TrEMBL) Submitted Name of Target Chain                       96337 non-null    object
 46   UniProt (TrEMBL) Entry Name of Target Chain                           96337 non-null    object
 47   UniProt (TrEMBL) Primary ID of Target Chain                           97644 non-null    object
 48   UniProt (TrEMBL) Secondary ID(s) of Target Chain                      9211 non-null     object
 49   UniProt (TrEMBL) Alternative ID(s) of Target Chain                    0 non-null        float64
 50   BindingDB Target Chain Sequence.1                                     147351 non-null   object
 51   PDB ID(s) of Target Chain.1                                           116325 non-null   object
 52   UniProt (SwissProt) Recommended Name of Target Chain.1                146100 non-null   object
 53   UniProt (SwissProt) Entry Name of Target Chain.1                      146100 non-null   object
 54   UniProt (SwissProt) Primary ID of Target Chain.1                      146100 non-null   object
 55   UniProt (SwissProt) Secondary ID(s) of Target Chain.1                 130223 non-null   object
 56   UniProt (SwissProt) Alternative ID(s) of Target Chain.1               0 non-null        float64
 57   UniProt (TrEMBL) Submitted Name of Target Chain.1                     1043 non-null     object
 58   UniProt (TrEMBL) Entry Name of Target Chain.1                         1043 non-null     object
 59   UniProt (TrEMBL) Primary ID of Target Chain.1                         1080 non-null     object
 60   UniProt (TrEMBL) Secondary ID(s) of Target Chain.1                    12 non-null       object
 61   UniProt (TrEMBL) Alternative ID(s) of Target Chain.1                  0 non-null        float64
 62   BindingDB Target Chain Sequence.2                                     35454 non-null    object
 63   PDB ID(s) of Target Chain.2                                           21574 non-null    object
 64   UniProt (SwissProt) Recommended Name of Target Chain.2                35435 non-null    object
 65   UniProt (SwissProt) Entry Name of Target Chain.2                      35435 non-null    object
 66   UniProt (SwissProt) Primary ID of Target Chain.2                      35435 non-null    object
 67   UniProt (SwissProt) Secondary ID(s) of Target Chain.2                 32698 non-null    object
 68   UniProt (SwissProt) Alternative ID(s) of Target Chain.2               0 non-null        float64
 69   UniProt (TrEMBL) Submitted Name of Target Chain.2                     19 non-null       object
 70   UniProt (TrEMBL) Entry Name of Target Chain.2                         19 non-null       object
 71   UniProt (TrEMBL) Primary ID of Target Chain.2                         19 non-null       object
 72   UniProt (TrEMBL) Secondary ID(s) of Target Chain.2                    11 non-null       object
 73   UniProt (TrEMBL) Alternative ID(s) of Target Chain.2                  0 non-null        float64
 74   BindingDB Target Chain Sequence.3                                     15372 non-null    object
 75   PDB ID(s) of Target Chain.3                                           10394 non-null    object
 76   UniProt (SwissProt) Recommended Name of Target Chain.3                15371 non-null    object
 77   UniProt (SwissProt) Entry Name of Target Chain.3                      15371 non-null    object
 78   UniProt (SwissProt) Primary ID of Target Chain.3                      15371 non-null    object
 79   UniProt (SwissProt) Secondary ID(s) of Target Chain.3                 12503 non-null    object
 80   UniProt (SwissProt) Alternative ID(s) of Target Chain.3               0 non-null        float64
 81   UniProt (TrEMBL) Submitted Name of Target Chain.3                     1 non-null        object
 82   UniProt (TrEMBL) Entry Name of Target Chain.3                         1 non-null        object
 83   UniProt (TrEMBL) Primary ID of Target Chain.3                         1 non-null        object
 84   UniProt (TrEMBL) Secondary ID(s) of Target Chain.3                    0 non-null        float64
 85   UniProt (TrEMBL) Alternative ID(s) of Target Chain.3                  0 non-null        float64
 86   BindingDB Target Chain Sequence.4                                     8497 non-null     object
 87   PDB ID(s) of Target Chain.4                                           2881 non-null     object
 88   UniProt (SwissProt) Recommended Name of Target Chain.4                8496 non-null     object
 89   UniProt (SwissProt) Entry Name of Target Chain.4                      8496 non-null     object
 90   UniProt (SwissProt) Primary ID of Target Chain.4                      8496 non-null     object
 91   UniProt (SwissProt) Secondary ID(s) of Target Chain.4                 6593 non-null     object
 92   UniProt (SwissProt) Alternative ID(s) of Target Chain.4               0 non-null        float64
 93   UniProt (TrEMBL) Submitted Name of Target Chain.4                     1 non-null        object
 94   UniProt (TrEMBL) Entry Name of Target Chain.4                         1 non-null        object
 95   UniProt (TrEMBL) Primary ID of Target Chain.4                         1 non-null        object
 96   UniProt (TrEMBL) Secondary ID(s) of Target Chain.4                    0 non-null        float64
 97   UniProt (TrEMBL) Alternative ID(s) of Target Chain.4                  0 non-null        float64
 98   BindingDB Target Chain Sequence.5                                     3921 non-null     object
 99   PDB ID(s) of Target Chain.5                                           3663 non-null     object
 100  UniProt (SwissProt) Recommended Name of Target Chain.5                3919 non-null     object
 101  UniProt (SwissProt) Entry Name of Target Chain.5                      3919 non-null     object
 102  UniProt (SwissProt) Primary ID of Target Chain.5                      3919 non-null     object
 103  UniProt (SwissProt) Secondary ID(s) of Target Chain.5                 3803 non-null     object
 104  UniProt (SwissProt) Alternative ID(s) of Target Chain.5               0 non-null        float64
 105  UniProt (TrEMBL) Submitted Name of Target Chain.5                     2 non-null        object
 106  UniProt (TrEMBL) Entry Name of Target Chain.5                         2 non-null        object
 107  UniProt (TrEMBL) Primary ID of Target Chain.5                         2 non-null        object
 108  UniProt (TrEMBL) Secondary ID(s) of Target Chain.5                    0 non-null        float64
 109  UniProt (TrEMBL) Alternative ID(s) of Target Chain.5                  0 non-null        float64
 110  BindingDB Target Chain Sequence.6                                     3108 non-null     object
 111  PDB ID(s) of Target Chain.6                                           85 non-null       object
 112  UniProt (SwissProt) Recommended Name of Target Chain.6                3107 non-null     object
 113  UniProt (SwissProt) Entry Name of Target Chain.6                      3107 non-null     object
 114  UniProt (SwissProt) Primary ID of Target Chain.6                      3107 non-null     object
 115  UniProt (SwissProt) Secondary ID(s) of Target Chain.6                 3059 non-null     object
 116  UniProt (SwissProt) Alternative ID(s) of Target Chain.6               0 non-null        float64
 117  UniProt (TrEMBL) Submitted Name of Target Chain.6                     1 non-null        object
 118  UniProt (TrEMBL) Entry Name of Target Chain.6                         1 non-null        object
 119  UniProt (TrEMBL) Primary ID of Target Chain.6                         1 non-null        object
 120  UniProt (TrEMBL) Secondary ID(s) of Target Chain.6                    0 non-null        float64
 121  UniProt (TrEMBL) Alternative ID(s) of Target Chain.6                  0 non-null        float64
 122  BindingDB Target Chain Sequence.7                                     3106 non-null     object
 123  PDB ID(s) of Target Chain.7                                           2468 non-null     object
 124  UniProt (SwissProt) Recommended Name of Target Chain.7                3104 non-null     object
 125  UniProt (SwissProt) Entry Name of Target Chain.7                      3104 non-null     object
 126  UniProt (SwissProt) Primary ID of Target Chain.7                      3104 non-null     object
 127  UniProt (SwissProt) Secondary ID(s) of Target Chain.7                 3032 non-null     object
 128  UniProt (SwissProt) Alternative ID(s) of Target Chain.7               0 non-null        float64
 129  UniProt (TrEMBL) Submitted Name of Target Chain.7                     2 non-null        object
 130  UniProt (TrEMBL) Entry Name of Target Chain.7                         2 non-null        object
 131  UniProt (TrEMBL) Primary ID of Target Chain.7                         2 non-null        object
 132  UniProt (TrEMBL) Secondary ID(s) of Target Chain.7                    0 non-null        float64
 133  UniProt (TrEMBL) Alternative ID(s) of Target Chain.7                  0 non-null        float64
 134  BindingDB Target Chain Sequence.8                                     3054 non-null     object
 135  PDB ID(s) of Target Chain.8                                           2700 non-null     object
 136  UniProt (SwissProt) Recommended Name of Target Chain.8                3054 non-null     object
 137  UniProt (SwissProt) Entry Name of Target Chain.8                      3054 non-null     object
 138  UniProt (SwissProt) Primary ID of Target Chain.8                      3054 non-null     object
 139  UniProt (SwissProt) Secondary ID(s) of Target Chain.8                 3054 non-null     object
 140  UniProt (SwissProt) Alternative ID(s) of Target Chain.8               0 non-null        float64
 141  UniProt (TrEMBL) Submitted Name of Target Chain.8                     0 non-null        float64
 142  UniProt (TrEMBL) Entry Name of Target Chain.8                         0 non-null        float64
 143  UniProt (TrEMBL) Primary ID of Target Chain.8                         0 non-null        float64
 144  UniProt (TrEMBL) Secondary ID(s) of Target Chain.8                    0 non-null        float64
 145  UniProt (TrEMBL) Alternative ID(s) of Target Chain.8                  0 non-null        float64
 146  BindingDB Target Chain Sequence.9                                     2424 non-null     object
 147  PDB ID(s) of Target Chain.9                                           1 non-null        object
 148  UniProt (SwissProt) Recommended Name of Target Chain.9                2424 non-null     object
 149  UniProt (SwissProt) Entry Name of Target Chain.9                      2424 non-null     object
 150  UniProt (SwissProt) Primary ID of Target Chain.9                      2424 non-null     object
 151  UniProt (SwissProt) Secondary ID(s) of Target Chain.9                 2413 non-null     object
 152  UniProt (SwissProt) Alternative ID(s) of Target Chain.9               0 non-null        float64
 153  UniProt (TrEMBL) Submitted Name of Target Chain.9                     0 non-null        float64
 154  UniProt (TrEMBL) Entry Name of Target Chain.9                         0 non-null        float64
 155  UniProt (TrEMBL) Primary ID of Target Chain.9                         0 non-null        float64
 156  UniProt (TrEMBL) Secondary ID(s) of Target Chain.9                    0 non-null        float64
 157  UniProt (TrEMBL) Alternative ID(s) of Target Chain.9                  0 non-null        float64
 158  BindingDB Target Chain Sequence.10                                    2422 non-null     object
 159  PDB ID(s) of Target Chain.10                                          337 non-null      object
 160  UniProt (SwissProt) Recommended Name of Target Chain.10               2422 non-null     object
 161  UniProt (SwissProt) Entry Name of Target Chain.10                     2422 non-null     object
 162  UniProt (SwissProt) Primary ID of Target Chain.10                     2422 non-null     object
 163  UniProt (SwissProt) Secondary ID(s) of Target Chain.10                2394 non-null     object
 164  UniProt (SwissProt) Alternative ID(s) of Target Chain.10              0 non-null        float64
 165  UniProt (TrEMBL) Submitted Name of Target Chain.10                    0 non-null        float64
 166  UniProt (TrEMBL) Entry Name of Target Chain.10                        0 non-null        float64
 167  UniProt (TrEMBL) Primary ID of Target Chain.10                        0 non-null        float64
 168  UniProt (TrEMBL) Secondary ID(s) of Target Chain.10                   0 non-null        float64
 169  UniProt (TrEMBL) Alternative ID(s) of Target Chain.10                 0 non-null        float64
 170  BindingDB Target Chain Sequence.11                                    29 non-null       object
 171  PDB ID(s) of Target Chain.11                                          0 non-null        float64
 172  UniProt (SwissProt) Recommended Name of Target Chain.11               29 non-null       object
 173  UniProt (SwissProt) Entry Name of Target Chain.11                     29 non-null       object
 174  UniProt (SwissProt) Primary ID of Target Chain.11                     29 non-null       object
 175  UniProt (SwissProt) Secondary ID(s) of Target Chain.11                29 non-null       object
 176  UniProt (SwissProt) Alternative ID(s) of Target Chain.11              0 non-null        float64
 177  UniProt (TrEMBL) Submitted Name of Target Chain.11                    0 non-null        float64
 178  UniProt (TrEMBL) Entry Name of Target Chain.11                        0 non-null        float64
 179  UniProt (TrEMBL) Primary ID of Target Chain.11                        0 non-null        float64
 180  UniProt (TrEMBL) Secondary ID(s) of Target Chain.11                   0 non-null        float64
 181  UniProt (TrEMBL) Alternative ID(s) of Target Chain.11                 0 non-null        float64
 182  BindingDB Target Chain Sequence.12                                    0 non-null        float64
 183  PDB ID(s) of Target Chain.12                                          0 non-null        float64
 184  UniProt (SwissProt) Recommended Name of Target Chain.12               0 non-null        float64
 185  UniProt (SwissProt) Entry Name of Target Chain.12                     0 non-null        float64
 186  UniProt (SwissProt) Primary ID of Target Chain.12                     0 non-null        float64
 187  UniProt (SwissProt) Secondary ID(s) of Target Chain.12                0 non-null        float64
 188  UniProt (SwissProt) Alternative ID(s) of Target Chain.12              0 non-null        float64
 189  UniProt (TrEMBL) Submitted Name of Target Chain.12                    0 non-null        float64
 190  UniProt (TrEMBL) Entry Name of Target Chain.12                        0 non-null        float64
 191  UniProt (TrEMBL) Primary ID of Target Chain.12                        0 non-null        float64
 192  UniProt (TrEMBL) Secondary ID(s) of Target Chain.12                   0 non-null        float64
 193  UniProt (TrEMBL) Alternative ID(s) of Target Chain.12                 0 non-null        float64

# 2. Converting 'Temp (C)' from object to float

In [4]:
# Extract numeric values from 'Temp (C)' column
df_org['Temp_C_float'] = df_org['Temp (C)'].str.extract(r'([-+]?\d+\.\d+)').astype(float)
df_org['Temp_C_float'].value_counts()

Temp_C_float
 25.00      112215
 37.00       36685
 22.00       17126
 30.00       14576
 4.00         6811
 23.00        4993
 20.00        1280
 40.00        1275
 27.00        1062
 0.00          583
 60.00         578
 28.00         462
 50.00         432
-80.00         413
 21.00         327
 1.00          309
 24.00         303
 10.00         266
 38.00         119
 7.50          119
 65.00          99
 15.00          93
 1390.75        72
 2.00           62
 1663.90        54
 32.00          49
 571.30         48
-248.15         46
-70.00          41
 844.45         36
 1117.60        36
 14.00          35
 48.00          33
 18.00          32
 5.00           29
 26.00          28
 35.00          25
 80.00          19
 310.15         16
 22.50          16
 16.00          16
 55.00          13
 293.15         12
 34.00          11
 25.50          10
 303.15          8
 36.00           7
 298.15          5
 11.00           5
 834.45          4
 70.00           3
 31.00           1
 43.00           1
 2.70            1
 7.70            1
 42.00           1
 3.60            1
 3.50            1
Name: count, dtype: int64

# 3. Drop rows with missing IC50

In [5]:
# Drop rows with NaN values in 'IC50 (nM)' column
df_org = df_org.dropna(subset=['IC50 (nM)'])

# Check the number of rows in the resulting DataFrame
df_org.shape[0]

1916275

# 4. Filtering: TgDHFR only

In [6]:
# Select temperatures of 25 degrees Celsius
# Ensure that all elements are strings
df_org['PDB ID(s) of Target Chain'] = df_org['PDB ID(s) of Target Chain'].astype(str)

# Check if '5T6A' is in the contents of the 'PDB ID(s) of Target Chain' column
contains_5T6A = df_org['PDB ID(s) of Target Chain'].apply(lambda x: '7FGX' in x.split(','))

# Filter the DataFrame to show only rows where 'contains_5T6A' is True
TgDHFR_rows = df_org[contains_5T6A].copy()

# Display the results
TgDHFR_rows.head()

,BindingDB Reactant_set_id,Ligand SMILES,Ligand InChI,Ligand InChI Key,BindingDB MonomerID,BindingDB Ligand Name,Target Name,Target Source Organism According to Curator or DataSource,Ki (nM),IC50 (nM),...,UniProt (SwissProt) Entry Name of Target Chain.12,UniProt (SwissProt) Primary ID of Target Chain.12,UniProt (SwissProt) Secondary ID(s) of Target Chain.12,UniProt (SwissProt) Alternative ID(s) of Target Chain.12,UniProt (TrEMBL) Submitted Name of Target Chain.12,UniProt (TrEMBL) Entry Name of Target Chain.12,UniProt (TrEMBL) Primary ID of Target Chain.12,UniProt (TrEMBL) Secondary ID(s) of Target Chain.12,UniProt (TrEMBL) Alternative ID(s) of Target Chain.12,Temp_C_float
32533,32537,COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O,InChI=1S/C19H22N4O4/c1-26-15-9-12(6-4-3-5-7-16...,MDVRFMJVQMAYTM-UHFFFAOYSA-N,18223,"6-{3-[(2,4-diaminopyrimidin-5-yl)methyl]-4,5-d...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32534,32538,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,IEDVJHCEMCRBQM-UHFFFAOYSA-N,18069,"5-[(3,4,5-trimethoxyphenyl)methyl]pyrimidine-2...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,2800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32535,32539,COc1ccc(OC)c(Cc2cnc3nc(N)nc(N)c3c2C)c1,InChI=1S/C17H19N5O2/c1-9-11(6-10-7-12(23-2)4-5...,VJXSSYDSOJBUAV-UHFFFAOYSA-N,18224,"6-[(2,5-dimethoxyphenyl)methyl]-5-methylpyrido...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32536,32540,COc1ccc(OCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,InChI=1S/C20H23N5O4/c1-11-13(10-23-19-17(11)18...,XDSAURPJEDMHGD-UHFFFAOYSA-N,18225,"2,4-diamino-5-deazapteridine, 4::4-[3-({2,4-di...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32537,32541,COc1ccc(OCCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,InChI=1S/C21H25N5O4/c1-12-14(11-24-20-18(12)19...,DANSKWKWCHMDDE-UHFFFAOYSA-N,18226,"2,4-diamino-5-deazapteridine, 5::5-[3-({2,4-di...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
TgDHFR_rows['Target Name'].value_counts()

Target Name
Bifunctional dihydrofolate reductase-thymidylate synthase    1364
Name: count, dtype: int64

In [8]:
TgDHFR_rows['Temp_C_float'].value_counts()

Temp_C_float
25.0    12
30.0     6
Name: count, dtype: int64

In [9]:
TgDHFR_rows['pH'].value_counts()

pH
7.4    14
7.0    12
Name: count, dtype: int64

In [11]:
TgDHFR_rows.shape

(1364, 195)

In [12]:
TgDHFR_rows['Temp_C_float'].value_counts()

Temp_C_float
25.0    12
30.0     6
Name: count, dtype: int64

In [13]:
TgDHFR_rows.reset_index(drop=True, inplace=True)

# 5. Converting IC50 nM to floats

In [14]:
# Remove symbols '<' and '>'
TgDHFR_rows['IC50 (nM)'] = TgDHFR_rows['IC50 (nM)'].str.replace(r'[<>]', '', regex=True)

# Convert the values to float
TgDHFR_rows['IC50 (nM)'] = TgDHFR_rows['IC50 (nM)'].astype(float)

# Print the DataFrame with 'IC50 (nM)' column converted to float
TgDHFR_rows['IC50 (nM)'].head(5)

0      34.0
1    2800.0
2       4.3
3       1.9
4       2.3
Name: IC50 (nM), dtype: float64

In [15]:
TgDHFR_rows['IC50 (nM)'].max()

500000.0

In [16]:
# Check if any values are greater than 100,000,000
mask = TgDHFR_rows['IC50 (nM)'] > 100000000

# Substitute values greater than 100,000,000 with 100,000,000
TgDHFR_rows.loc[mask, 'IC50 (nM)'] = 100000000

In [17]:
TgDHFR_rows['IC50 (nM)'].max()

500000.0

In [18]:
TgDHFR_rows.to_csv('V2-1-database-all_TgDHFR_BindingDB.csv', index=False)

In [20]:
TgDHFR_rows['PubChem CID'].nunique()

805

# 6. Dublicates: avareging IC50

In [51]:
# Renaming a single column
TgDHFR_rows = TgDHFR_rows.rename(columns={'Ligand SMILES': 'Smiles'})

In [52]:
TgDHFR_rows['Smiles'].nunique()

805

In [53]:
# Checking duplicates:
# Identify rows with identical values in both 'Ligand SMILES' and 'BindingDB Target Chain Sequence'
df_dupl = TgDHFR_rows[TgDHFR_rows.duplicated(subset=['Smiles'], keep=False)]

# Show the duplicates
df_dupl.shape

(871, 196)

In [54]:
# Group by 'PubChem CID' and then display the 'pH' and 'IC50 (nM)' for each group
grouped_dupl = df_dupl.groupby('Smiles')[['IC50 (nM)','pIC50 Value']]

# Convert to a list for display or further processing
grouped_dupl_list = grouped_dupl.apply(lambda x: x.reset_index(drop=True)).reset_index()

# Display the result
grouped_dupl_list.head()

,Smiles,level_1,IC50 (nM),pIC50 Value
0,CC(C)c1c(Sc2c(C)cccc2C)[nH]c2nc(N)nc(N)c12,0,13000.0,4.886057
1,CC(C)c1c(Sc2c(C)cccc2C)[nH]c2nc(N)nc(N)c12,1,300.0,6.522879
2,CC(C)c1c(Sc2c(Cl)cccc2Cl)[nH]c2nc(N)nc(N)c12,0,2200.0,5.657577
3,CC(C)c1c(Sc2c(Cl)cccc2Cl)[nH]c2nc(N)nc(N)c12,1,520.0,6.283997
4,CC(C)c1c(Sc2ccc(Cl)c(Cl)c2)[nH]c2nc(N)nc(N)c12,0,2300.0,5.638272

## 6.1. Step 1: Remove Outliers

In [55]:
import pandas as pd

# Function to remove outliers using the IQR method
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

# Apply the outlier removal function to each group
grouped_dupl_list_no_outliers = grouped_dupl_list.groupby('Smiles').apply(lambda group: remove_outliers_iqr(group, 'IC50 (nM)')).reset_index(drop=True)

# Display the cleaned DataFrame without outliers
grouped_dupl_list_no_outliers.head(10)

/scratch/nvs/job_33154273/ipykernel_252940/2061142521.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_dupl_list_no_outliers = grouped_dupl_list.groupby('Smiles').apply(lambda group: remove_outliers_iqr(group, 'IC50 (nM)')).reset_index(drop=True)

,Smiles,level_1,IC50 (nM),pIC50 Value
0,CC(C)c1c(Sc2c(C)cccc2C)[nH]c2nc(N)nc(N)c12,0,13000.0,4.886057
1,CC(C)c1c(Sc2c(C)cccc2C)[nH]c2nc(N)nc(N)c12,1,300.0,6.522879
2,CC(C)c1c(Sc2c(Cl)cccc2Cl)[nH]c2nc(N)nc(N)c12,0,2200.0,5.657577
3,CC(C)c1c(Sc2c(Cl)cccc2Cl)[nH]c2nc(N)nc(N)c12,1,520.0,6.283997
4,CC(C)c1c(Sc2ccc(Cl)c(Cl)c2)[nH]c2nc(N)nc(N)c12,0,2300.0,5.638272
5,CC(C)c1c(Sc2ccc(Cl)c(Cl)c2)[nH]c2nc(N)nc(N)c12,1,1400.0,5.853872
6,CC(C)c1c(Sc2ccc3ccccc3c2)[nH]c2nc(N)nc(N)c12,0,2400.0,5.619789
7,CC(C)c1c(Sc2ccc3ccccc3c2)[nH]c2nc(N)nc(N)c12,1,1500.0,5.823909
8,CC(C)c1c(Sc2cccc3ccccc23)[nH]c2nc(N)nc(N)c12,0,12000.0,4.920819
9,CC(C)c1c(Sc2cccc3ccccc23)[nH]c2nc(N)nc(N)c12,1,120.0,6.920819

## 6.2. Step 2: Calculate Average IC50:

In [56]:
# Calculate the average of log_IC50 for each group in grouped_dupl_tg_list_no_outliers
average_ic50_df = grouped_dupl_list_no_outliers.groupby(['Smiles'], as_index=False)['IC50 (nM)'].mean()

# Rename the column for clarity
average_ic50_df.rename(columns={'IC50 (nM)': 'IC50 (nM) Avg'}, inplace=True)

# Display the resulting DataFrame with BindingDB Target Chain Sequence, Ligand SMILES, and their average log_IC50 values
average_ic50_df

                                             Smiles  IC50 (nM) Avg
0        CC(C)c1c(Sc2c(C)cccc2C)[nH]c2nc(N)nc(N)c12        6650.00
1      CC(C)c1c(Sc2c(Cl)cccc2Cl)[nH]c2nc(N)nc(N)c12        1360.00
2    CC(C)c1c(Sc2ccc(Cl)c(Cl)c2)[nH]c2nc(N)nc(N)c12        1850.00
3      CC(C)c1c(Sc2ccc3ccccc3c2)[nH]c2nc(N)nc(N)c12        1950.00
4      CC(C)c1c(Sc2cccc3ccccc23)[nH]c2nc(N)nc(N)c12        6060.00
..                                              ...            ...
307     Nc1ncc(N2CCN(CC2)c2cccc(c2)-c2ncccn2)c(N)n1          27.25
308      Nc1ncc(N2CCN(CC2)c2cccc(c2)C(F)(F)F)c(N)n1          61.85
309         Nc1ncc(N2CCN(CC2)c2cccc(c2)C2CC2)c(N)n1          28.90
310                Nc1ncc(N2CCN(CC2)c2ccccc2)c(N)n1         209.00
311       Nc1ncc(N2CCN(CC2)c2ccccc2-c2ccccc2)c(N)n1          30.95

[312 rows x 2 columns]

In [58]:
# Remove duplicates based on 'Ligand SMILES' and 'BindingDB Target Chain Sequence'
# Keep the first occurrence and drop the rest
df_ic50_cleaned = TgDHFR_rows.drop_duplicates(subset=['Smiles'], keep='first')

# Display the cleaned DataFrame
df_ic50_cleaned.shape

(805, 196)

In [59]:
df_ic50_cleaned.head()

,BindingDB Reactant_set_id,Smiles,Ligand InChI,Ligand InChI Key,BindingDB MonomerID,BindingDB Ligand Name,Target Name,Target Source Organism According to Curator or DataSource,Ki (nM),IC50 (nM),...,UniProt (SwissProt) Primary ID of Target Chain.12,UniProt (SwissProt) Secondary ID(s) of Target Chain.12,UniProt (SwissProt) Alternative ID(s) of Target Chain.12,UniProt (TrEMBL) Submitted Name of Target Chain.12,UniProt (TrEMBL) Entry Name of Target Chain.12,UniProt (TrEMBL) Primary ID of Target Chain.12,UniProt (TrEMBL) Secondary ID(s) of Target Chain.12,UniProt (TrEMBL) Alternative ID(s) of Target Chain.12,Temp_C_float,pIC50 Value
0,32537,COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O,InChI=1S/C19H22N4O4/c1-26-15-9-12(6-4-3-5-7-16...,MDVRFMJVQMAYTM-UHFFFAOYSA-N,18223,"6-{3-[(2,4-diaminopyrimidin-5-yl)methyl]-4,5-d...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.468521
1,32538,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,IEDVJHCEMCRBQM-UHFFFAOYSA-N,18069,"5-[(3,4,5-trimethoxyphenyl)methyl]pyrimidine-2...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,2800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.552842
2,32539,COc1ccc(OC)c(Cc2cnc3nc(N)nc(N)c3c2C)c1,InChI=1S/C17H19N5O2/c1-9-11(6-10-7-12(23-2)4-5...,VJXSSYDSOJBUAV-UHFFFAOYSA-N,18224,"6-[(2,5-dimethoxyphenyl)methyl]-5-methylpyrido...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.366532
3,32540,COc1ccc(OCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,InChI=1S/C20H23N5O4/c1-11-13(10-23-19-17(11)18...,XDSAURPJEDMHGD-UHFFFAOYSA-N,18225,"2,4-diamino-5-deazapteridine, 4::4-[3-({2,4-di...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.721246
4,32541,COc1ccc(OCCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C,InChI=1S/C21H25N5O4/c1-12-14(11-24-20-18(12)19...,DANSKWKWCHMDDE-UHFFFAOYSA-N,18226,"2,4-diamino-5-deazapteridine, 5::5-[3-({2,4-di...",Bifunctional dihydrofolate reductase-thymidyla...,NaN,NaN,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.638272

## 6.3. Step 3: Substitute IC50 values in duplicated cases to average

In [60]:
# Merge the two dataframes on the 'BindingDB Target Chain Sequence' and 'Ligand SMILES' columns
df_ic50_cleaned = df_ic50_cleaned.merge(
    average_ic50_df,
    on=['Smiles'],
    how='left'
)

# Substitute the 'log_IC50' values in merged_df_cleaned with 'Average log_IC50' where available
df_ic50_cleaned['IC50 (nM)'] = df_ic50_cleaned['IC50 (nM) Avg'].combine_first(df_ic50_cleaned['IC50 (nM)'])

# Drop the 'Average log_IC50' column as it's no longer needed
df_ic50_cleaned = df_ic50_cleaned.drop(columns=['IC50 (nM) Avg'])

# Display the updated DataFrame
df_ic50_cleaned[['Smiles', 'IC50 (nM)']].head(10)

                                            Smiles  IC50 (nM)
0        COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O     34.000
1                  COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC   2722.000
2           COc1ccc(OC)c(Cc2cnc3nc(N)nc(N)c3c2C)c1     14.224
3     COc1ccc(OCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C      1.900
4    COc1ccc(OCCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C      2.300
5   COc1ccc(OCCCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C      2.000
6   COc1ccc(OCCCC(O)=O)c(Cc2cnc3nc(N)nc(N)c3c2C)c1      2.300
7    COc1ccc(cc1Cc1cnc2nc(N)nc(N)c2c1C)C#CCCC(O)=O      0.460
8   COc1ccc(cc1Cc1cnc2nc(N)nc(N)c2c1C)C#CCCCC(O)=O      4.300
9  COc1ccc(cc1Cc1cnc2nc(N)nc(N)c2c1C)C#CCCCCC(O)=O      3.200

## 6.4. Converting IC50 (nM) to pIC50

In [62]:
# Convert values from nanomolar to molar and take the log10
df_ic50_cleaned['pIC50 Value'] = -np.log10(df_ic50_cleaned['IC50 (nM)'] / 1e9)

df_ic50_cleaned[['Smiles','IC50 (nM)','pIC50 Value']].head(4)

                                         Smiles  IC50 (nM)  pIC50 Value
0     COc1cc(cc(Cc2cnc(N)nc2N)c1OC)C#CCCCC(O)=O     34.000     7.468521
1               COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC   2722.000     5.565112
2        COc1ccc(OC)c(Cc2cnc3nc(N)nc(N)c3c2C)c1     14.224     7.846978
3  COc1ccc(OCCCC(O)=O)cc1Cc1cnc2nc(N)nc(N)c2c1C      1.900     8.721246

In [63]:
df_ic50_cleaned.shape

(805, 196)

In [64]:
#Save df
df_ic50_cleaned.to_csv('BindingDB_TgDHFR.csv', index=False)